# Generated by Django 6.1 on 2026-08-14 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rxcui', models.CharField(max_length=20, unique=True)),
                ('rxnorm_name', models.CharField(max_length=500)),
                ('tty', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'db_table': 'medicines',
            },
        ),
    ]
