# Generated by Django 6.1 on 2026-08-14 03:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0002_add_timestamps_to_medicine'),
    ]

    operations = [
        migrations.CreateModel(
            name='DDInterDrugMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ddinter_drug_name', models.CharField(max_length=500, unique=True)),
                ('mapping_method', models.CharField(blank=True, default='', max_length=100)),
                ('mapping_status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ddinter_mappings', to='medicines.medicine')),
            ],
            options={
                'db_table': 'ddinter_drug_mappings',
                'constraints': [models.UniqueConstraint(fields=('ddinter_drug_name',), name='unique_ddinter_drug_name')],
            },
        ),
    ]
