"""What comes *out* of the AI layer.

The rule this module exists to enforce is AGENTS.md section 11: anyone consuming
an explanation must be able to tell the verified data apart from the generated
text. So both travel together in one object, labelled.
"""

from __future__ import annotations

from dataclasses import dataclass, field

from .interaction import InteractionFact

DEFAULT_DISCLAIMER = (
    "This explanation was generated by an AI assistant from reference data. "
    "It is not medical advice. Talk to your doctor or pharmacist before "
    "changing how you take any medicine."
)


@dataclass(frozen=True)
class Explanation:
    """A generated explanation together with the verified facts behind it.

    `text` is model output and must be treated as such by every consumer.
    `facts` is carried through unchanged from the request, so a caller can
    always render the source data rather than the generated prose.
    """

    text: str
    facts: tuple[InteractionFact, ...]
    model: str
    disclaimer: str = DEFAULT_DISCLAIMER
    generated_by_ai: bool = True

    @property
    def sources(self) -> tuple[str, ...]:
        """Distinct attributions across the underlying facts, for display."""
        return tuple(dict.fromkeys(fact.source for fact in self.facts))


@dataclass(frozen=True)
class NoInteractionResult:
    """The answer when the reference data contains no relevant interaction.

    Deliberately not an Explanation: AGENTS.md section 11 forbids implying that
    "nothing found" means "safe", so this carries fixed wording rather than
    anything a model wrote.
    """

    checked_medicines: tuple[str, ...]
    sources_checked: tuple[str, ...]
    message: str = (
        "No interaction between these medicines was found in the reference data "
        "we checked. That is not the same as confirming they are safe together. "
        "Ask your doctor or pharmacist if you have any concerns."
    )
    generated_by_ai: bool = field(default=False, init=False)
