import React, { createContext, useState, useContext, useEffect } from 'react';

const LanguageContext = createContext();

export const translations = {
  en: {
    // Auth / Login / Signup
    welcomeBack: "Welcome Back",
    loginSubtitle: "Login to your account to manage your medication safety.",
    email: "Email",
    password: "Password",
    login: "Login",
    dontHaveAccount: "Don't have an account?",
    signUp: "Sign up",
    emailRequired: "Email address is required",
    validEmail: "Please enter a valid email address",
    passwordRequired: "Password is required",
    loginFailed: "Login failed. Please try again.",
    forgotPassword: "Forgot password?",
    enterPasswordPlaceholder: "Enter your password",
    resetPasswordTitle: "Reset your password",
    resetPasswordSub: "Enter your email address and we'll send you a link to reset your password.",
    resetSuccessAlert: "If an account with that email exists, you'll receive a reset link shortly. Check your inbox (and spam folder).",
    backToSignIn: "← Back to sign in",
    sendResetLink: "Send reset link",
    tooManyAttempts: "Too many attempts. Please wait a moment and try again.",
    setNewPasswordTitle: "Set new password",
    setNewPasswordSub: "Choose a strong password for your MediGuard account.",
    passwordUpdatedSuccess: "Password updated! Redirecting you to sign in…",
    updatePasswordBtn: "Update password",
    newPasswordLabel: "New Password",
    confirmNewPasswordLabel: "Confirm New Password",
    reEnterNewPasswordPlaceholder: "Re-enter your new password",
    newPasswordRequired: "New password is required.",
    confirmNewPasswordRequired: "Please confirm your new password.",
    passwordDifferentFromCurrent: "New password must be different from your current password.",
    passwordTooWeak: "Password is too weak. Please choose a stronger password.",
    unableToUpdatePassword: "Unable to update password. Please try again or request a new reset link.",
    backToResults: "Back to Results",
    backToHistory: "Back to History",

    
    // Sidebar
    menu: "Menu",
    dashboard: "Dashboard",
    myMedicines: "My Medicines",
    safetyCheck: "Safety Check",
    history: "History",
    profile: "Profile",
    account: "Account",
    settings: "Settings",
    logout: "Logout",

    // Dashboard Overview
    goodMorning: "Good morning",
    greetingText: "Here's your medication safety overview.",
    safetyOverview: "Safety Overview",
    currentStatus: "Current Status",
    totalMedicines: "Total Medicines",
    interactionsFound: "Interactions Found",
    lastSafetyCheck: "Last Safety Check",
    attentionRequired: "Attention Required",
    safe: "Safe",
    quickActions: "Quick Actions",
    runSafetyCheck: "Run Safety Check",
    addNewMedicine: "Add New Medicine",
    recentHistory: "Recent History",
    viewAllHistory: "View All History",
    viewDetails: "View Details",
    noHistoryText: "No safety checks conducted yet.",

    // Dashboard components extra
    currentMedicines: "Current Medicines",
    activeMedCabinet: "Active medication cabinet",
    medicine: "medicine",
    medicines: "medicines",
    unableToLoadMeds: "Unable to load your medicines.",
    noMedsAddedYet: "No medicines added yet.",
    addMedsSupportingText: "Add your current medicines to keep your medication profile up to date.",
    recentSafetyChecks: "Recent Safety Checks",
    screeningHistory: "Interaction screening history",
    viewAll: "View All",
    unableToLoadRecentChecks: "Unable to load recent checks.",
    noSafetyChecksYet: "No safety checks yet.",
    startASafetyCheck: "Start a safety check",
    today: "Today",
    noInteractions: "No interactions identified",
    warningCount: "warning",
    warningsCount: "warnings",
    moderateWarning: "moderate warning",
    activeWarnings: "Active Warnings",
    activeWarning: "Active Warning",
    noActiveWarnings: "No Active Warnings",
    safetyOverviewDesc: "Potential medication interactions need your attention.",
    safetyOverviewSafeDesc: "All checked medicines are safe. No interactions found.",
    safetyStatusUnavailable: "Safety status unavailable",
    safetyStatusUnavailableDesc: "Run a safety screening to evaluate potential drug-drug interaction risks across your medication list.",
    checkSafety: "Check Safety",
    startSafetyCheck: "Start Safety Check",
    lastCheckedLabel: "Last checked",

    // Medicines
    cabinetTitle: "My Medicine Cabinet",
    cabinetSubtitle: "Manage your active prescriptions and check for compatibility.",
    addMedicineBtn: "Add Medicine",
    searchPlaceholder: "Search medicines...",
    noMedicines: "No medicines in your cabinet yet. Add some to get started!",
    addMedPopupTitle: "Add New Medicine",
    drugNameLabel: "Drug Name",
    dosageLabel: "Dosage (e.g., 50mg)",
    frequencyLabel: "Frequency (e.g., Once daily)",
    purposeLabel: "Purpose (optional)",
    cancelBtn: "Cancel",
    confirmAddBtn: "Add to Cabinet",
    deleteTooltip: "Delete medicine",
    saveMedicine: "Save Medicine",
    demoNotice: "Demo Mode: Newly added medicines persist locally in state. Connect backend API to save to database.",

    // Safety Check
    safetyCheckTitle: "Safety Check",
    safetyCheckSubtitle: "Check compatibility of medicines in your cabinet.",
    checkBtn: "Check My Medicines",
    checkingProgress: "Checking your medicines...",
    checkingBtnLabel: "Checking...",
    statusLabel: "Safety Status Summary",
    statusSafeMsg: "All checked medicines are safe. No interactions found.",
    statusDangerMsg: "Attention Required: Potential interaction risks detected.",
    interactionSubtitle: "Click to interact",
    evidenceAndSources: "Evidence & Sources",
    unableToComplete: "Unable to complete safety check",
    somethingWentWrong: "Something went wrong while checking your medicines. Please try again.",
    tryAgain: "Try Again",
    severe: "Severe",
    moderate: "Moderate",
    minor: "Minor",
    unknownRisk: "Unknown Risk",
    databaseHint: "The screening check will run against the DDInter 2.0 interaction database.",
    safetyCabinetTitle: "Medication Screening Cabinet",
    safetyCabinetSub: "Preview list of medicines that will be checked for safety risks",
    noInteractionsTitle: "No interactions found",
    noInteractionsSub: "Your current medicines have no interactions to display.",
    severeOverallMsg: "severe interaction(s) require your attention. Please review your safety results.",
    moderateOverallMsg: "moderate interaction(s) identified. Review details for safety advice.",
    safetyCabinetEmpty: "Your medication cabinet is currently empty. Add your daily medicines under My Medicines to screen for safety risks.",
    addMedicinesToCabinet: "Add Medicines to Cabinet",
    
    // Mock interaction descriptions
    warfarinAspirinDesc: "Increased risk of bleeding.",
    amlodipineSimvastatinDesc: "Simvastatin may increase the blood levels of Amlodipine.",
    noKnownInteractionsDesc: "No known drug-drug interactions found.",
    insufficientEvidenceDesc: "Insufficient interaction evidence available.",

    // History
    historyTitle: "Safety Check History",
    historySubtitle: "View your previous medication safety checks.",
    noHistory: "No history available.",
    medicinesChecked: "medicines checked",
    medicineChecked: "medicine checked",
    interactionFound: "interaction found",
    interactionsFoundCount: "interactions found",
    viewDetailsBtn: "View Details",
    clearHistoryBtn: "Clear History",
    clearHistoryConfirm: "Are you sure you want to clear your safety check history?",
    screenCabinetToRecord: "Screen your medication cabinet to record safety check history.",

    // History Details & Interaction Details
    historyDetailsTitle: "Safety Check Details",
    medicinesCheckedLabel: "Medicines Checked",
    whatDoesThisMean: "What does this mean?",
    whatToWatchFor: "What to watch for?",
    whatShouldYouDo: "What should you do?",
    aiPlaceholderText: "AI-generated information will appear here.",
    interactionDetailsTitle: "Interaction Details",
    interactionLabel: "Interaction",
    sourceIndicator: "Source",
    nihReference: "Supporting clinical reference and documentation regarding concomitant administration risks.",
    fdaReference: "Post-marketing surveillance and active safety communications database.",
    pdrReference: "Official guidelines on drug-to-drug interactions classifications and outcomes.",
    at: "at",
    
    // Health Profile Form Onboarding
    onboardingTitle: "Complete Your Profile",
    onboardingSubtitle: "Please provide your health profile details to personalize checks.",
    dateOfBirth: "Date of Birth",
    gender: "Gender",
    selectGender: "Select gender",
    male: "Male",
    female: "Female",
    other: "Other",
    allergies: "Known Allergies (separated by comma)",
    chronicConditions: "Chronic Conditions (separated by comma)",
    saveProfileBtn: "Save Profile",

    // Profile & Settings
    editProfile: "Edit Health Profile",
    viewProfile: "Health Profile",
    fullName: "Full Name",
    saveChanges: "Save Changes",
    cancel: "Cancel",
    generalSettings: "General Settings",
    themeLabel: "App Theme",
    lightMode: "Light Mode",
    darkMode: "Dark Mode",
    profileTitle: "Profile",
    profileSubtitle: "Your personal health information",
    editProfileBtn: "Edit Profile",
    profileUpdateSuccess: "Profile updated successfully.",
    readOnlyLabel: "Read-only",
    nameLabel: "Name",
    emailLabel: "Email",
    ageLabel: "Age",
    medicalHistoryLabel: "Medical History",
    regularMedicinesLabel: "Regular Medicines",
    noneLabel: "None",
    notAvailableLabel: "Not available",
    savingStatusLabel: "Saving...",
    loadingProfile: "Loading profile...",
    medHistoryRequired: "Medical history is required. If you have no major medical history, type NONE.",
    unableToSaveProfile: "Unable to save your profile. Please try again.",
    medHistoryPlaceholder: "e.g. Diabetes, Thyroid or NONE",
    regularMedsPlaceholder: "e.g. Paracetamol, Metformin",
    settingsTitle: "Account Settings",
    settingsSubtitle: "Manage security, notification preferences, and privacy",
    settingsPlaceholder: "Settings Placeholder — Security, notification triggers, and password reset options will be managed here.",

    // Onboarding additional
    ageRequired: "Age is required",
    ageWholeNumber: "Age must be a valid whole number",
    ageGreaterThanZero: "Age must be greater than zero",
    ageRealistic: "Please enter a realistic age (1-120)",
    conditionsRequired: "Medical conditions is required. Type 'NONE' if no major history.",
    onboardingSaveError: "Something went wrong while saving your information. Please try again.",
    onboardingIntroTitle: "Tell us a little about yourself",
    onboardingIntroSub: "Help us personalize your medication safety experience.",
    agePlaceholder: "e.g. 28",
    conditionsPlaceholder: "e.g. Diabetes, Asthma, or NONE",
    conditionsHintText: "If no major medical history, type 'NONE'.",
    medsInputPlaceholder: "Search/type medicine name...",
    addBtn: "Add",
    confirmBtn: "Confirm",

    // Registration / Signup specific
    fullNameRequired: "Full name is required",
    nameMinLength: "Name must be at least 2 characters",
    passwordMinLength: "Password must be at least 8 characters",
    passwordNumRequired: "Password must contain at least one number",
    confirmPasswordRequired: "Please confirm your password",
    passwordsDontMatch: "Passwords do not match",
    registerFailed: "Registration failed. Please try again.",
    createAccountTitle: "Create your account",
    registerSubtitle: "Join MediGuard for personalized medicine safety checks and drug interaction monitoring.",
    registerSuccessMsg: "Account created successfully! Please log in to continue.",
    fullNameLabel: "Full Name",
    fullNamePlaceholder: "e.g. Sarah Jenkins",
    emailPlaceholder: "name@example.com",
    passwordPlaceholder: "Create a strong password",
    hidePassword: "Hide password",
    showPassword: "Show password",
    passwordMustInclude: "Password must include:",
    minChars: "At least 8 characters",
    minNumber: "At least one number (0-9)",
    minLetter: "At least one letter",
    confirmPasswordLabel: "Confirm Password",
    confirmPasswordPlaceholder: "Re-enter your password",
    createAccountBtn: "Create Account",
    alreadyHaveAccount: "Already have an account?",
    registerDisclaimer: "By creating an account, you agree to MediGuard's Terms of Service and Privacy Policy. MediGuard provides medication safety insights and does not replace professional medical advice.",
    joinNetworkTitle: "Join MediGuard Safety Network",
    joinNetworkSub: "Create an account to start screening prescriptions, tracking medication histories, and preventing adverse drug interactions.",
    rxNormStandardized: "RxNorm Standardized",
    freeSafetyTools: "100% Free Safety Tools",

    // Header context keys
    networkPortalTag: "MediGuard Safety Network",
    user: "User",
    closeMenu: "Close menu",
    openMenu: "Open menu",
    notifications: "Notifications",
    loginHeroTagline: "Smart Medicine Safety & Drug Interaction Assistant",
    loginHeroDesc: "Verify prescription combinations, identify interaction risks, and protect patient safety with evidence-backed intelligence.",
    loginHeroBadge1: "DDInter 2.0 Verified",
    loginHeroBadge2: "Patient Safety Screening",

    // New features translations
    landingBadge: "🛡️ Smarter Medication Safety",
    landingTitle1: "Your Medicines.",
    landingTitle2: "Your Safety.",
    landingTitle3: "Simplified.",
    landingSubtitle: "Easily manage your daily medications, screen for potential drug-drug interactions, and get clear, patient-friendly safety insights in seconds.",
    landingGetStarted: "Get Started",
    landingLogin: "Login",
    landingAlreadyAccount: "Already have an account?",
    landingNavHome: "Home",
    landingNavFeatures: "Features",
    landingNavHowItWorks: "How It Works",
    landingNavPreview: "Preview",
    landingWhyTitle: "Why MediGuard?",
    landingWhySubtitle: "Everything you need to keep your medication routine safe and organized.",
    landingCard1Title: "Manage Medicines",
    landingCard1Desc: "Keep your current medications organized in one clean, centralized cabinet.",
    landingCard2Title: "Check Medication Safety",
    landingCard2Desc: "Review your active prescriptions and supplements for potential safety concerns.",
    landingCard3Title: "Understand Interactions",
    landingCard3Desc: "Get clear, patient-friendly explanations when potential drug interactions are identified.",
    landingCard4Title: "Simple, Understandable Results",
    landingCard4Desc: "Turn complex medical data into easy-to-understand guidance you can trust.",
    landingHowTitle: "How It Works",
    landingHowSubtitle: "Three simple steps to smarter medication management.",
    landingStep1Num: "01",
    landingStep1Title: "Add Medicines",
    landingStep1Desc: "Enter your active daily prescriptions and supplements into your secure cabinet.",
    landingStep2Num: "02",
    landingStep2Title: "Run Safety Check",
    landingStep2Desc: "Screen your full medication list against our verified drug interaction database.",
    landingStep3Num: "03",
    landingStep3Title: "Understand Results",
    landingStep3Desc: "Receive clear safety warnings, risk classifications, and actionable guidance.",
    landingPreviewTitle: "Built for Clarity & Peace of Mind",
    landingPreviewSubtitle: "Preview how MediGuard organizes your medications and screens for risks.",
    landingPreviewCabinetTitle: "Current Medicines",
    landingPreviewSafetyTitle: "Safety Overview",
    landingPreviewSafeStatus: "✓ No major interaction detected",
    landingDisclaimer: "MediGuard is designed to provide medication information and safety insights. It does not replace professional medical advice.",
    landingBottomCtaTitle: "Take a clearer look at your medication safety.",
    landingFooterDesc: "Medication management and safety insights, designed to make complex information easier to understand.",
    landingCopyright: "© 2026 MediGuard. All rights reserved.",

    landingPreviewCount: "3 medicines",
    landingPreviewSevere: "Severe Warnings",
    landingPreviewModerate: "Moderate Warnings",
    landingPreviewSafe: "Checked Safe",
    landingPreviewDemo: "Demo Profile",
    landingHeroFloating1: "100% Patient Centric",
    landingHeroFloating2: "Instant Interaction Screening",
    landingPreviewSafetyCheckHeader: "MediGuard Safety Check",
    landingPreviewSafetyStatus: "Safety Status",
    landingPreviewSafeMsg: "Interaction engine active & verified",

    setReminderTime: "Set Reminder Time",
    selectHour: "Select Hour",
    selectMinute: "Select Minute",
    hourTabLabel: "Hour",
    minuteTabLabel: "Minute",
    doneBtn: "Done",
    reminderTimeLabel: "Reminder Time",
    addTimeBtn: "+ Add Time",

    notificationsPanelTitle: "Notifications",
    markAllRead: "Mark all as read",
    noNewNotifications: "No new notifications",
    allCaughtUp: "You're all caught up with your medicine reminders.",
    medicineReminderCategory: "Medicine Reminder",
    notifMessagePre: "It's time for your ",
    notifMessagePost: " reminder.",
    clickToMarkRead: "Click to mark read",
    loadingNotifications: "Loading notifications...",
    unableToLoadNotifications: "Unable to load notifications.",
    tryAgainBtn: "Try again",
  },
  hi: {

    // Auth / Login / Signup
    welcomeBack: "स्वागत है",
    loginSubtitle: "अपनी दवा सुरक्षा प्रबंधित करने के लिए अपने खाते में लॉग इन करें।",
    email: "ईमेल",
    password: "पासवर्ड",
    login: "लॉग इन करें",
    dontHaveAccount: "खाता नहीं है?",
    signUp: "Sign up",
    emailRequired: "ईमेल पता आवश्यक है",
    validEmail: "कृपया एक मान्य ईमेल पता दर्ज करें",
    passwordRequired: "पासवर्ड आवश्यक है",
    loginFailed: "लॉगिन विफल रहा। कृपया पुनः प्रयास करें।",
    forgotPassword: "पासवर्ड भूल गए?",
    enterPasswordPlaceholder: "अपना पासवर्ड दर्ज करें",
    resetPasswordTitle: "अपना पासवर्ड रीसेट करें",
    resetPasswordSub: "अपना ईमेल पता दर्ज करें और हम आपको अपना पासवर्ड रीसेट करने के लिए एक लिंक भेजेंगे।",
    resetSuccessAlert: "यदि उस ईमेल वाला कोई खाता मौजूद है, तो आपको जल्द ही एक रीसेट लिंक प्राप्त होगा। अपना इनबॉक्स (और स्पैम फ़ोल्डर) जांचें।",
    backToSignIn: "← लॉगिन पर वापस जाएं",
    sendResetLink: "रीसेट लिंक भेजें",
    tooManyAttempts: "बहुत सारे प्रयास। कृपया थोड़ी देर प्रतीक्षा करें और पुन: प्रयास करें।",
    setNewPasswordTitle: "नया पासवर्ड सेट करें",
    setNewPasswordSub: "अपने MediGuard खाते के लिए एक मजबूत पासवर्ड चुनें।",
    passwordUpdatedSuccess: "पासवर्ड अपडेट हो गया! आपको साइन इन पर रीडायरेक्ट कर रहे हैं...",
    updatePasswordBtn: "पासवर्ड अपडेट करें",
    newPasswordLabel: "नया पासवर्ड",
    confirmNewPasswordLabel: "नए पासवर्ड की पुष्टि करें",
    reEnterNewPasswordPlaceholder: "अपना नया पासवर्ड पुनः दर्ज करें",
    newPasswordRequired: "नया पासवर्ड आवश्यक है।",
    confirmNewPasswordRequired: "कृपया अपने नए पासवर्ड की पुष्टि करें।",
    passwordDifferentFromCurrent: "नया पासवर्ड आपके वर्तमान पासवर्ड से भिन्न होना चाहिए।",
    passwordTooWeak: "पासवर्ड बहुत कमजोर है। कृपया एक मजबूत पासवर्ड चुनें।",
    unableToUpdatePassword: "पासवर्ड अपडेट करने में असमर्थ। कृपया पुनः प्रयास करें या एक नया रीसेट लिंक मांगें।",
    backToResults: "परिणामों पर वापस जाएं",
    backToHistory: "इतिहास पर वापस जाएं",


    // Sidebar
    menu: "मेन्यू",
    dashboard: "डैशबोर्ड",
    myMedicines: "मेरी दवाएं",
    safetyCheck: "सुरक्षा जांच",
    history: "इतिहास",
    profile: "प्रोफ़ाइल",
    account: "खाता",
    settings: "सेटिंग्स",
    logout: "लॉग आउट",

    // Dashboard Overview
    goodMorning: "शुभ प्रभात",
    greetingText: "ये रहा आपकी दवा सुरक्षा का सारांश।",
    safetyOverview: "दवा सुरक्षा विवरण",
    currentStatus: "वर्तमान स्थिति",
    totalMedicines: "कुल दवाएं",
    interactionsFound: "परस्पर प्रभाव मिले",
    lastSafetyCheck: "अंतिम सुरक्षा जांच",
    attentionRequired: "ध्यान देने की आवश्यकता है",
    safe: "सुरक्षित",
    quickActions: "त्वरित कार्रवाई",
    runSafetyCheck: "सुरक्षा जांच चलाएं",
    addNewMedicine: "नई दवा जोड़ें",
    recentHistory: "हाल का इतिहास",
    viewAllHistory: "सभी इतिहास देखें",
    viewDetails: "विवरण देखें",
    noHistoryText: "अभी तक कोई सुरक्षा जांच नहीं की गई है।",

    // Dashboard components extra
    currentMedicines: "सक्रिय दवाएं",
    activeMedCabinet: "सक्रिय दवा कैबिनेट",
    medicine: "दवा",
    medicines: "दवाएं",
    unableToLoadMeds: "दवाएं लोड करने में असमर्थ।",
    noMedsAddedYet: "अभी तक कोई दवा नहीं जोड़ी गई है।",
    addMedsSupportingText: "अपने दवा प्रोफ़ाइल को अद्यतित रखने के लिए अपनी वर्तमान दवाएं जोड़ें।",
    recentSafetyChecks: "हाल की सुरक्षा जांच",
    screeningHistory: "परस्पर प्रभाव जांच का इतिहास",
    viewAll: "सभी देखें",
    unableToLoadRecentChecks: "हाल की जांच लोड करने में असमर्थ।",
    noSafetyChecksYet: "अभी तक कोई सुरक्षा जांच नहीं की गई है।",
    startASafetyCheck: "सुरक्षा जांच शुरू करें",
    today: "आज",
    noInteractions: "कोई परस्पर प्रभाव नहीं मिला",
    warningCount: "चेतावनी",
    warningsCount: "चेतावनी",
    moderateWarning: "मध्यम चेतावनी",
    activeWarnings: "सक्रिय चेतावनियां",
    activeWarning: "सक्रिय चेतावनी",
    noActiveWarnings: "कोई सक्रिय चेतावनी नहीं",
    safetyOverviewDesc: "संभावित दवा चेतावनियों पर ध्यान दें।",
    safetyOverviewSafeDesc: "सभी जांची गई दवाएं सुरक्षित हैं। कोई परस्पर प्रभाव नहीं मिला।",
    safetyStatusUnavailable: "सुरक्षा स्थिति अनुपलब्ध",
    safetyStatusUnavailableDesc: "संभावित दवा प्रतिक्रिया प्रभावों का मूल्यांकन करने के लिए सुरक्षा स्क्रीन चलाएं।",
    checkSafety: "सुरक्षा जांचें",
    startSafetyCheck: "सुरक्षा जांच शुरू करें",
    lastCheckedLabel: "अंतिम बार जांचा गया",

    // Medicines
    cabinetTitle: "मेरी दवा की अलमारी",
    cabinetSubtitle: "अपने सक्रिय नुस्खे प्रबंधित करें और अनुकूलता की जांच करें।",
    addMedicineBtn: "दवा जोड़ें",
    searchPlaceholder: "दवाएं खोजें...",
    noMedicines: "आपकी अलमारी में अभी तक कोई दवा नहीं है। शुरू करने के लिए कुछ जोड़ें!",
    addMedPopupTitle: "नई दवा जोड़ें",
    drugNameLabel: "दवा का नाम",
    dosageLabel: "खुराक (जैसे, 50mg)",
    frequencyLabel: "आवृत्ति (जैसे, दिन में एक बार)",
    purposeLabel: "उद्देश्य (वैकल्पिक)",
    cancelBtn: "रद्द करें",
    confirmAddBtn: "अलमारी में जोड़ें",
    deleteTooltip: "दवा हटाएं",
    saveMedicine: "दवा सहेजें",
    demoNotice: "डेमो मोड: नई जोड़ी गई दवाएं स्थानीय स्टेट में सुरक्षित रहती हैं। डेटाबेस में सहेजने के लिए बैकएंड एपीआई कनेक्ट करें।",

    // Safety Check
    safetyCheckTitle: "सुरक्षा जांच",
    safetyCheckSubtitle: "अपनी अलमारी में दवाओं की अनुकूलता की जांच करें।",
    checkBtn: "मेरी दवाओं की जांच करें",
    checkingProgress: "आपकी दवाओं की जांच की जा रही है...",
    checkingBtnLabel: "जांच की जा रही है...",
    statusLabel: "सुरक्षा स्थिति सारांश",
    statusSafeMsg: "सभी जांची गई दवाएं सुरक्षित हैं। कोई परस्पर प्रभाव नहीं मिला।",
    statusDangerMsg: "ध्यान दें: संभावित परस्पर प्रभाव के खतरों का पता चला है।",
    interactionSubtitle: "परस्पर प्रभाव देखने के लिए क्लिक करें",
    evidenceAndSources: "साक्ष्य और स्रोत",
    unableToComplete: "सुरक्षा जांच पूरी करने में असमर्थ",
    somethingWentWrong: "आपकी दवाओं की जांच करते समय कुछ गलत हो गया। कृपया दोबारा प्रयास करें।",
    tryAgain: "पुनः प्रयास करें",
    severe: "गंभीर",
    moderate: "मध्यम",
    minor: "मामूली",
    unknownRisk: "अज्ञात जोखिम",
    databaseHint: "स्क्रीनिंग जांच DDInter 2.0 परस्पर प्रभाव डेटाबेस के विरुद्ध चलाई जाएगी।",
    safetyCabinetTitle: "दवा स्क्रीनिंग अलमारी",
    safetyCabinetSub: "उन दवाओं की पूर्वावलोकन सूची जिनकी सुरक्षा खतरों के लिए जांच की जाएगी",
    noInteractionsTitle: "कोई परस्पर प्रभाव नहीं मिला",
    noInteractionsSub: "आपकी वर्तमान दवाओं में प्रदर्शित करने के लिए कोई परस्पर प्रभाव नहीं है।",
    severeOverallMsg: "गंभीर परस्पर प्रभाव मिले जिनपर ध्यान देने की आवश्यकता है। कृपया सुरक्षा परिणाम देखें।",
    moderateOverallMsg: "मध्यम परस्पर प्रभाव मिले। सुरक्षा सलाह के लिए विवरण देखें।",
    safetyCabinetEmpty: "आपकी दवा अलमारी वर्तमान में खाली है। सुरक्षा जोखिमों की जांच के लिए 'मेरी दवाएं' में अपनी दवाएं जोड़ें।",
    addMedicinesToCabinet: "अलमारी में दवाएं जोड़ें",
    
    // Mock interaction descriptions
    warfarinAspirinDesc: "रक्तस्राव का बढ़ा हुआ खतरा।",
    amlodipineSimvastatinDesc: "सिमवास्टेटिन एम्लोडिपाइन के रक्त स्तर को बढ़ा सकता है।",
    noKnownInteractionsDesc: "कोई ज्ञात दवा-दवा परस्पर प्रभाव नहीं मिला।",
    insufficientEvidenceDesc: "अपर्याप्त परस्पर प्रभाव साक्ष्य उपलब्ध हैं।",

    // History
    historyTitle: "सुरक्षा जांच इतिहास",
    historySubtitle: "अपनी पिछली दवा सुरक्षा जांच देखें।",
    noHistory: "कोई इतिहास उपलब्ध नहीं है।",
    medicinesChecked: "दवाएं जांची गईं",
    medicineChecked: "दवा जांची गई",
    interactionFound: "परस्पर प्रभाव मिला",
    interactionsFoundCount: "परस्पर प्रभाव मिले",
    viewDetailsBtn: "विवरण देखें",
    clearHistoryBtn: "इतिहास मिटायें",
    clearHistoryConfirm: "क्या आप वाकई अपना सुरक्षा जांच इतिहास मिटाना चाहते हैं?",
    screenCabinetToRecord: "सुरक्षा जांच इतिहास रिकॉर्ड करने के लिए अपनी दवा कैबिनेट की जांच करें।",

    // History Details & Interaction Details
    historyDetailsTitle: "सुरक्षा जांच विवरण",
    medicinesCheckedLabel: "जांची गई दवाएं",
    whatDoesThisMean: "इसका क्या मतलब है?",
    whatToWatchFor: "किस बात का ध्यान रखना चाहिए?",
    whatShouldYouDo: "आपको क्या करना चाहिए?",
    aiPlaceholderText: "एआई-जनित जानकारी यहां दिखाई देगी।",
    interactionDetailsTitle: "परस्पर प्रभाव विवरण",
    interactionLabel: "परस्पर प्रभाव",
    sourceIndicator: "स्रोत",
    nihReference: "सहवर्ती प्रशासन जोखिमों के संबंध में सहायक नैदानिक संदर्भ और दस्तावेज।",
    fdaReference: "मार्केटिंग के बाद की निगरानी और सक्रिय दवा सुरक्षा संचार डेटाबेस।",
    pdrReference: "दवा-दवा परस्पर प्रभावों के वर्गीकरण और परिणामों पर आधिकारिक दिशानिर्देश।",
    at: "को",

    // Health Profile Form Onboarding
    onboardingTitle: "अपनी प्रोफ़ाइल पूरी करें",
    onboardingSubtitle: "जांच को व्यक्तिगत बनाने के लिए कृपया अपने स्वास्थ्य प्रोफ़ाइल की जानकारी दें।",
    dateOfBirth: "जन्म तिथि",
    gender: "लिंग",
    selectGender: "लिंग चुनें",
    male: "पुरुष",
    female: "महिला",
    other: "अन्य",
    allergies: "ज्ञात एलर्जी (अल्पविराम से अलग करें)",
    chronicConditions: "पुरानी बीमारियां (अल्पविराम से अलग करें)",
    saveProfileBtn: "प्रोफ़ाइल सहेजें",

    // Profile & Settings
    editProfile: "स्वास्थ्य प्रोफ़ाइल संपादित करें",
    viewProfile: "स्वास्थ्य प्रोफ़ाइल",
    fullName: "पूरा नाम",
    saveChanges: "परिवर्तन सहेजें",
    cancel: "रद्द करें",
    generalSettings: "सामान्य सेटिंग्स",
    themeLabel: "ऐप थीम",
    lightMode: "LIGHT MODE",
    darkMode: "DARK MODE",
    profileTitle: "प्रोफ़ाइल",
    profileSubtitle: "आपकी व्यक्तिगत स्वास्थ्य जानकारी",
    editProfileBtn: "प्रोफ़ाइल संपादित करें",
    profileUpdateSuccess: "प्रोफ़ाइल सफलतापूर्वक अपडेट की गई।",
    readOnlyLabel: "केवल पढ़ने के लिए",
    nameLabel: "नाम",
    emailLabel: "ईमेल",
    ageLabel: "उम्र",
    medicalHistoryLabel: "चिकित्सा इतिहास",
    regularMedicinesLabel: "नियमित दवाएं",
    noneLabel: "कोई नहीं",
    notAvailableLabel: "अनुपलब्ध",
    savingStatusLabel: "सहेजा जा रहा है...",
    loadingProfile: "प्रोफ़ाइल लोड हो रहा है...",
    medHistoryRequired: "चिकित्सा इतिहास आवश्यक है। यदि आपके पास कोई चिकित्सा इतिहास नहीं है, तो NONE टाइप करें।",
    unableToSaveProfile: "आपकी प्रोफ़ाइल सहेजने में असमर्थ। कृपया पुनः प्रयास करें।",
    medHistoryPlaceholder: "जैसे मधुमेह, थायराइड या NONE",
    regularMedsPlaceholder: "जैसे पैरासिटामोल, मेटफॉर्मिन",
    settingsTitle: "खाता सेटिंग्स",
    settingsSubtitle: "सुरक्षा, अधिसूचना प्राथमिकताएं और गोपनीयता प्रबंधित करें",
    settingsPlaceholder: "सेटिंग्स प्लेसहोल्डर - सुरक्षा, अधिसूचना ट्रिगर और पासवर्ड रीसेट विकल्प यहां प्रबंधित किए जाएंगे।",

    // Onboarding additional
    ageRequired: "आयु आवश्यक है",
    ageWholeNumber: "आयु एक वैध पूर्ण संख्या होनी चाहिए",
    ageGreaterThanZero: "आयु शून्य से अधिक होनी चाहिए",
    ageRealistic: "कृपया एक वास्तविक आयु दर्ज करें (1-120)",
    conditionsRequired: "चिकित्सकीय स्थिति आवश्यक है। यदि कोई गंभीर बीमारी नहीं है तो 'NONE' लिखें।",
    onboardingSaveError: "आपकी जानकारी सहेजते समय कुछ गलत हो गया। कृपया पुनः प्रयास करें।",
    onboardingIntroTitle: "हमें अपने बारे में थोड़ा बताएं",
    onboardingIntroSub: "अपनी दवा सुरक्षा अनुभव को व्यक्तिगत बनाने में हमारी सहायता करें।",
    agePlaceholder: "जैसे 28",
    conditionsPlaceholder: "जैसे मधुमेह, अस्थमा, या NONE",
    conditionsHintText: "यदि कोई गंभीर बीमारी का इतिहास नहीं है, तो 'NONE' लिखें।",
    medsInputPlaceholder: "दवा का नाम खोजें/लिखें...",
    addBtn: "जोड़ें",
    confirmBtn: "पुष्टि करें",

    // Registration / Signup specific
    fullNameRequired: "पूरा नाम आवश्यक है",
    nameMinLength: "नाम कम से कम 2 वर्णों का होना चाहिए",
    passwordMinLength: "पासवर्ड कम से कम 8 वर्णों का होना चाहिए",
    passwordNumRequired: "पासवर्ड में कम से कम एक संख्या होनी चाहिए",
    confirmPasswordRequired: "कृपया अपने पासवर्ड की पुष्टि करें",
    passwordsDontMatch: "पासवर्ड मेल नहीं खाते",
    registerFailed: "पंजीकरण विफल रहा। कृपया पुनः प्रयास करें।",
    createAccountTitle: "अपना खाता बनाएं",
    registerSubtitle: "व्यक्तिगत दवा सुरक्षा जांच और दवा परस्पर प्रभाव निगरानी के लिए MediGuard में शामिल हों।",
    registerSuccessMsg: "खाता सफलतापूर्वक बन गया! जारी रखने के लिए कृपया लॉग इन करें।",
    fullNameLabel: "पूरा नाम",
    fullNamePlaceholder: "जैसे सारा जेन्किंस",
    emailPlaceholder: "name@example.com",
    passwordPlaceholder: "एक मजबूत पासवर्ड बनाएं",
    hidePassword: "पासवर्ड छिपाएं",
    showPassword: "पासवर्ड दिखाएं",
    passwordMustInclude: "पासवर्ड में शामिल होना चाहिए:",
    minChars: "कम से कम 8 वर्ण",
    minNumber: "कम से कम एक संख्या (0-9)",
    minLetter: "कम से कम एक अक्षर",
    confirmPasswordLabel: "पासवर्ड की पुष्टि करें",
    confirmPasswordPlaceholder: "अपना पासवर्ड पुनः दर्ज करें",
    createAccountBtn: "खाता बनाएं",
    alreadyHaveAccount: "पहले से ही एक खाता है?",
    registerDisclaimer: "खाता बनाकर, आप MediGuard की सेवा की शर्तों और गोपनीयता नीति से सहमत होते हैं। MediGuard दवा सुरक्षा अंतर्दृष्टि प्रदान करता है और पेशेवर चिकित्सा सलाह को प्रतिस्थापित नहीं करता है।",
    joinNetworkTitle: "MediGuard सुरक्षा नेटवर्क में शामिल हों",
    joinNetworkSub: "नुस्खों की जांच करने, दवा के इतिहास को ट्रैक करने और दवा परस्पर प्रभाव को रोकने के लिए एक खाता बनाएं।",
    rxNormStandardized: "RxNorm मानकीकृत",
    freeSafetyTools: "100% निःशुल्क सुरक्षा उपकरण",

    // Header context keys
    networkPortalTag: "MediGuard सुरक्षा नेटवर्क",
    user: "उपयोगकर्ता",
    closeMenu: "मेन्यू बंद करें",
    openMenu: "मेन्यू खोलें",
    notifications: "अधिसूचनाएं",
    loginHeroTagline: "स्मार्ट दवा सुरक्षा और दवा परस्पर प्रभाव सहायक",
    loginHeroDesc: "सटीक नैदानिक ​​साक्ष्य के साथ दवाओं के संयोजनों की जांच करें, जोखिमों की पहचान करें और मरीज की सुरक्षा सुनिश्चित करें।",
    loginHeroBadge1: "DDInter 2.0 सत्यापित",
    loginHeroBadge2: "मरीज सुरक्षा स्क्रीनिंग",

    // New features translations
    landingBadge: "🛡️ समझदार दवा सुरक्षा",
    landingTitle1: "आपकी दवाएं।",
    landingTitle2: "आपकी सुरक्षा।",
    landingTitle3: "सरलीकृत।",
    landingSubtitle: "अपनी दैनिक दवाओं को आसानी से प्रबंधित करें, संभावित दवा-दवा इंटरैक्शन की जांच करें और सेकंडों में स्पष्ट सुरक्षा जानकारी प्राप्त करें।",
    landingGetStarted: "शुरू करें",
    landingLogin: "लॉग इन करें",
    landingAlreadyAccount: "क्या आपके पास पहले से एक खाता है?",
    landingNavHome: "होम",
    landingNavFeatures: "विशेषताएं",
    landingNavHowItWorks: "यह कैसे काम करता है",
    landingNavPreview: "पूर्वावलोकन",
    landingWhyTitle: "MediGuard क्यों?",
    landingWhySubtitle: "अपनी दवा की दिनचर्या को सुरक्षित और व्यवस्थित रखने के लिए आवश्यक सब कुछ।",
    landingCard1Title: "दवाएं प्रबंधित करें",
    landingCard1Desc: "अपनी वर्तमान दवाओं को एक स्वच्छ, केंद्रीकृत कैबिनेट में व्यवस्थित रखें।",
    landingCard2Title: "दवा सुरक्षा जांचें",
    landingCard2Desc: "संभावित सुरक्षा चिंताओं के लिए अपने सक्रिय नुस्खों और सप्लीमेंट्स की समीक्षा करें।",
    landingCard3Title: "इंटरैक्शन समझें",
    landingCard3Desc: "संभावित दवा इंटरैक्शन की पहचान होने पर स्पष्ट, रोगी-अनुकूल स्पष्टीकरण प्राप्त करें।",
    landingCard4Title: "सरल, समझने योग्य परिणाम",
    landingCard4Desc: "जटिल चिकित्सा डेटा को आसानी से समझ में आने वाले मार्गदर्शन में बदलें।",
    landingHowTitle: "यह कैसे काम करता है",
    landingHowSubtitle: "स्मार्ट दवा प्रबंधन के लिए तीन सरल कदम।",
    landingStep1Num: "01",
    landingStep1Title: "दवाएं जोड़ें",
    landingStep1Desc: "अपने सक्रिय दैनिक नुस्खों और सप्लीमेंट्स को अपने कैबिनेट में दर्ज करें।",
    landingStep2Num: "02",
    landingStep2Title: "सुरक्षा जांच चलाएं",
    landingStep2Desc: "सत्यापित दवा इंटरैक्शन डेटाबेस के विरुद्ध अपनी पूरी दवा सूची की जांच करें।",
    landingStep3Num: "03",
    landingStep3Title: "परिणाम समझें",
    landingStep3Desc: "स्पष्ट सुरक्षा चेतावनियाँ, जोखिम वर्गीकरण और कार्रवाई योग्य मार्गदर्शन प्राप्त करें।",
    landingPreviewTitle: "स्पष्टता और मानसिक शांति के लिए निर्मित",
    landingPreviewSubtitle: "पूर्वावलोकन करें कि कैसे MediGuard आपकी दवाओं को व्यवस्थित करता है।",
    landingPreviewCabinetTitle: "वर्तमान दवाएं",
    landingPreviewSafetyTitle: "सुरक्षा अवलोकन",
    landingPreviewSafeStatus: "✓ कोई प्रमुख इंटरैक्शन नहीं पाया गया",
    landingDisclaimer: "MediGuard दवा संबंधी जानकारी और सुरक्षा अंतर्दृष्टि प्रदान करने के लिए डिज़ाइन किया गया है। यह पेशेवर चिकित्सा सलाह का स्थान नहीं लेता है।",
    landingBottomCtaTitle: "अपनी दवा सुरक्षा को अधिक स्पष्टता से देखें।",
    landingFooterDesc: "दवा प्रबंधन और सुरक्षा अंतर्दृष्टि, जटिल जानकारी को समझने में आसान बनाने के लिए डिज़ाइन की गई है।",
    landingCopyright: "© 2026 MediGuard. सर्वाधिकार सुरक्षित।",

    landingPreviewCount: "3 दवाएं",
    landingPreviewSevere: "गंभीर चेतावनियाँ",
    landingPreviewModerate: "मध्यम चेतावनियाँ",
    landingPreviewSafe: "सुरक्षित पाया गया",
    landingPreviewDemo: "डेमो प्रोफ़ाइल",
    landingHeroFloating1: "100% मरीज केंद्रित",
    landingHeroFloating2: "तात्कालिक परस्पर प्रभाव स्क्रीनिंग",
    landingPreviewSafetyCheckHeader: "MediGuard सुरक्षा जांच",
    landingPreviewSafetyStatus: "सुरक्षा स्थिति",
    landingPreviewSafeMsg: "परस्पर प्रभाव इंजन सक्रिय और सत्यापित",

    setReminderTime: "रिमाइंडर समय सेट करें",
    selectHour: "घंटा चुनें",
    selectMinute: "मिनट चुनें",
    hourTabLabel: "घंटा",
    minuteTabLabel: "मिनट",
    doneBtn: "हो गया",
    reminderTimeLabel: "रिमाइंडर का समय",
    addTimeBtn: "+ समय जोड़ें",

    notificationsPanelTitle: "अधिसूचनाएं",
    markAllRead: "सभी को पढ़ा हुआ चिह्नित करें",
    noNewNotifications: "कोई नई अधिसूचना नहीं",
    allCaughtUp: "आप अपने दवा रिमाइंडर के साथ पूरी तरह से अपडेट हैं।",
    medicineReminderCategory: "दवा रिमाइंडर",
    notifMessagePre: "यह आपकी ",
    notifMessagePost: " दवा का समय है।",
    clickToMarkRead: "पढ़ा हुआ चिह्नित करने के लिए क्लिक करें",
    loadingNotifications: "अधिसूचनाएं लोड हो रही हैं...",
    unableToLoadNotifications: "अधिसूचनाएं लोड करने में असमर्थ।",
    tryAgainBtn: "पुनः प्रयास करें",
  }
};


export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('mediguard_language') || 'en';
  });

  useEffect(() => {
    localStorage.setItem('mediguard_language', language);
  }, [language]);

  const t = (key) => {
    return translations[language]?.[key] || translations['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
