# Generated by Django 6.1 on 2026-08-14 03:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicines', '0003_add_ddinter_drug_mapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('Major', 'Major'), ('Moderate', 'Moderate'), ('Minor', 'Minor')], max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('medicine_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interactions_as_a', to='medicines.medicine')),
                ('medicine_b', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interactions_as_b', to='medicines.medicine')),
            ],
            options={
                'db_table': 'drug_interactions',
                'constraints': [models.UniqueConstraint(fields=('medicine_a', 'medicine_b'), name='unique_drug_interaction_pair'), models.CheckConstraint(condition=models.Q(('medicine_a', models.F('medicine_b')), _negated=True), name='drug_interaction_different_medicines')],
            },
        ),
    ]
